### ISSUE TITLE
Add support for S3 Express One Zone [tracking]

### ISSUE THREAD

**Issue by rcoh** [awslabs/aws-sdk-rust#992]
### Describe the feature

Add Rust SDK support for S3 Express One Zone

### Use Case

Enable the Rust SDK to use One Zone buckets

### Proposed Solution

We have internally agreed-upon design to follow.

### Work breakdown

- [x] (smithy-rs#3386) Add placeholder types and enable control flow to be redirected for S3 Express use case
- [x] (smithy-rs#3388) Use create_session S3 API to obtain a session token for S3 Express
- [x] (smithy-rs#3388) Implement the signer for S3 Express (presigning & header signing)
- [x] (smithy-rs#3393) Modify S3 Express default for checksum
- [x] (smithy-rs#3390) Implement S3 Express identity cache
- [x] (smithy-rs#3433) Implement `DisableS3ExpressSessionAuth` (some part of the implementation is not supported until #1073 is addressed)
- [x] (smithy-rs#3462) Add various API tests in canary
- [x] (optional for initial release) - (smithy-rs#3446) Add benchmark to profile S3 Express use cases

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by HammadB** [comment]
I noticed this was marked as p1, is this actively being worked on / is their a timeline? Debating rolling my own

**Comment by shikhar** [comment]
@HammadB in case it helps, I found directory buckets to be usable with `disable_s3_express_session_auth(true)`, so I'm holding off for official support. I am seeing sub-20 ms rather than the promised sub-10 ms latencies though, which I am hopeful will improve with session-based auth.

**Comment by rcoh** [comment]
> I noticed this was marked as p1, is this actively being worked on / is their a timeline? Debating rolling my own
Yes this is in progress.
